### ISSUE TITLE
Document support for specifying the serviceAccountName for the pipeline run

### ISSUE THREAD

**Issue by jsight** [bigkevmcd/tekton-polling-operator#6]
In glancing through the code, it appears that it is supported to specify the serviceAccountName for the run. However, I can't find a reference to this in the documentation or examples?

**Comment by bigkevmcd** [comment]
Hi @jsight thanks for opening this issue, I've just added an example of this to the main documentation.

If there's anything else you'd like me to add, please feel free to either reopen or create a new issue.

thanks again,

Kevin McDermott

**Comment by jsight** [comment]
That's perfect, thanks for the addition!
